LeadingLog/reading-log

- .idea/.gitignore
- .idea/misc.xml
- .idea/modules.xml
- .idea/prettier.xml
- .idea/reading-log.iml
- .idea/vcs.xml
* X
<br/>
* idea 파일 삭제 (인텔리제이 설정파일)
<br/>
*
<br/>
*
> idea 파일 삭제

- ReadingLogFrontend/package-lock.json
- ReadingLogFrontend/package.json
- ReadingLogFrontend/src/components/common/CustomScrollbar.tsx
- ReadingLogFrontend/src/components/homeRight/TimeTracking.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxStopWatch.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxTimer.tsx
- ReadingLogFrontend/src/view/Main.tsx
- ReadingLogFrontend/tailwind.config.js
> 커스텀 스크롤 UI 구현

- ReadingLogFrontend/src/components/common/CustomScrollbar.tsx
- ReadingLogFrontend/src/components/homeRight/TimeTracking.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemStopWatch.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemTimer.tsx
- ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
- ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
- ReadingLogFrontend/src/components/homeTop/ModalCalendar.tsx
- ReadingLogFrontend/src/components/modal/ModalAlert.tsx
- ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
- ReadingLogFrontend/src/components/modal/ModalManager.tsx
- ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
- ReadingLogFrontend/src/components/modal/ModalNotice.tsx
- ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
- ReadingLogFrontend/src/store/modalStore.ts
- ReadingLogFrontend/src/types/modal.ts
- ReadingLogFrontend/tailwind.config.js
- ReadingLogFrontend/vite.config.ts
* 
<br/>
const {openModal,closeModal, closeAllModals} = useModalStore();  이렇게 모달열기, 지정 모달 닫기, 모든 모달 닫기 버튼으로 구성했습니다.
변수명을 지정하고 modal을 만들고 closeModal( 여기 닫고 싶은 모달 변수 명  ) 을 넣으면 해당 모달만 닫힙니다.
```javascript
/* 정지 버튼 클릭 시  */
const stopTimer = () => {
const firstModalId = openModal("ModalNotice", {
title: "독서를 종료하시나요?",
subTitle: "종료 시 시간이 저장돼요",
cancelText: "아니요 더 읽을래요!",
confirmText: "네 종료할게요!",
reverseBtn: true,
onConfirm: () => {
const secondModalId = openModal("ModalNotice", {
title: "독서시간 저장 완료!",
subTitle: "수고하셨어요!",
onlyConfirm: true,
confirmText: "닫기",
onConfirm: () => {
// 여기서 두 번째 모달 닫기
closeModal(secondModalId);
// 우측 콘텐츠 변경
setRightContent("TimeTracking", {
TimeTracking: { tab: "onlyMonthReadingList" },
});
// 초기화
setSeconds(0);
setMinute(0);
setHour(0); …
```
> 모달 컴포넌트 중복 표시 가능하도록 수정 및 알라딘 API 개발 중

- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecord.java
- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordService.java
- ReadingLogBackend/src/main/resources/Entity_SQL/reading_record.sql
* 25 
<br/>
*  ReadingRecord 개발 
<br/>
*
<br/>
*
> #25 독서통계 개발

- ReadingLogBackend/src/main/java/com/example/demo/response/ResponseService.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Controller/UserController.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Service/UserService.java
* #13 
<br/>
* - ResponseService 생성
* - 반환값 변경
<br/>
*
<br/>
*
> #13 : 이서연 : NaverLogin

- ReadingLogBackend/src/main/java/com/example/demo/user/Controller/UserController.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Repository/RefreshTokenRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Repository/UserRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Service/RefreshTokenService.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Service/UserService.java
* #13 
<br/>
* 마이페이지 조회
* 마이페이지 수정
* 
<br/>
*
<br/>
*
> #13 마이페이지 수정, 조회

- ReadingLogBackend/src/main/java/com/example/demo/user/Service/ApiKeyService.java
> Sycicdtest2

- ReadingLogBackend/src/main/java/com/example/demo/user/Service/ApiKeyService.java
- ReadingLogBackend/src/main/resources/application.properties
> Sycicdtest

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/components/common/YearSlideBar.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
- ReadingLogFrontend/src/store/modalStore.ts
- ReadingLogFrontend/tailwind.config.js
* #50 
<br/>
* 
<br/>
*
<br/>
*
> 타임라인 월 표시 UI 추가 및 년도 클릭 버튼 기능 추가

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/components/common/BookImgList.tsx
- ReadingLogFrontend/src/components/common/CustomScrollbar.tsx
- ReadingLogFrontend/src/components/common/YearSlideBar.tsx
- ReadingLogFrontend/src/components/homeLeft/MyBookList.tsx
- ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/StatsPage.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
- ReadingLogFrontend/src/store/modalStore.ts
- ReadingLogFrontend/tailwind.config.js
> 내 독서목록 탭 버튼 클릭 효과 추가 및 스크롤 UI 수정

- .github/workflows/gradle.yml
- ReadingLogBackend/src/main/java/com/example/demo/aladinApi/AladinController.java
*  #61 
<br/>
* 알라딘 API 조회 (isFavorite 은 추후 독서목록 개발 후 추가 개발 예정) 
<br/>
*
<br/>
*
> B aladin api

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
- ReadingLogFrontend/src/components/layout/LeftPage.tsx
> 탭코드 및 관심도서 목록 클릭 시 독서계획 추가 모달 표시

- ReadingLogFrontend/package-lock.json
- ReadingLogFrontend/package.json
- ReadingLogFrontend/public/mockServiceWorker.js
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/main.tsx
- ReadingLogFrontend/src/mocks/browser.ts
- ReadingLogFrontend/src/mocks/handlers.ts
- ReadingLogFrontend/src/mocks/handlers/bookHandlers.ts
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/mocks/handlers/readingRecordHandlers.ts
- ReadingLogFrontend/src/mocks/handlers/userHandlers.ts
- ReadingLogFrontend/src/view/social/OAuthCallbackHandler.tsx
* #62 
<br/>
* `npm install msw --save-dev` 로 msw를 설치하였습니다.
* `npx msw init public/ --save`를 사용하여 `public/mockServiceWorker.js` 파일을 생성했습니다.
* 개발 환경에서만 MSW가 동작하도록 `main.tsx` 에 설정을 추가했습니다.
* `Timeline.tsx`에 테스트용 요청 코드를 추가해둔 상태입니다. (참고용)
* Notion API에 명시된 response body를 핸들러 코드에 작성해두었습니다. 필요 시 수정하여 사용하시면 됩니다.
<br/>
*
<br/>
*
> MSW 설정 완료 및 기본 핸들러 추가

- ReadingLogFrontend/src/components/homeLeft/MyBookList.tsx
- ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
- ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
- ReadingLogFrontend/src/components/layout/LeftPage.tsx
- ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData.json
- ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData2.json
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/types/tabName.ts
- ReadingLogFrontend/tailwind.config.js
#66 
* 
<br/>
로컬에서 임시 데이터 사용해 관심도서 목록을 불러오도록 설정했습니다.
* 
<br/>
*
<br/>
*
> 관심도서 리스트 가져오기 (Mock 데이터 사용)

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/components/common/YearSlideBar.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/mocks/dummyData/timeLineReadingListData/ReadingList-2024.json
- ReadingLogFrontend/src/mocks/dummyData/timeLineReadingListData/ReadingList-2025.json
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/store/useDateStore.ts
* #68 
<br/>
* 
<br/>
*
<br/>
*
> 타임라인에 보여 질 년&월 도서 수 (Mock 데이터 사용) 

- .github/workflows/deploy.yml
- ReadingLogFrontend/vercel.json
* 
<br/>
* 배포 시 발생했던 404 에러를 해결하기 위해 `vercel.json` 파일을 추가하여 배포 경로를 올바르게 설정했습니다.
* 자동 배포 시 `vercel.json` 파일이 배포 과정에 포함될 수 있도록 `deploy.yml` 을 수정했습니다.
<br/>
*
<br/>
*
> vercel.json 설정 추가로 배포 시 404 에러 해결

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/api/ThisMonthReadingListApi.ts
- ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
- ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData2.json
- ReadingLogFrontend/src/mocks/dummyData/thisMonthReadingListData/thisMonthReadingList.json
- ReadingLogFrontend/src/mocks/dummyData/thisMonthReadingListData/thisMonthReadingList2.json
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/types/monthReadingList.ts
* #70 
<br/>
* 
<br/>
*
<br/>
*
> 이번 달 독서 리스트 가져오기 (Mock 데이터 사용)

- ReadingLogFrontend/src/api/timeLineReadingListApi.ts
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/types/monthReadingList.ts
- ReadingLogFrontend/src/types/timeLine.ts
*  
<br/>
* api 요청 시 header 부분 삭제 및 header 관련 목데이터 파일 수정
* 타입 정의 파일 추가 및 수정
- 타임라인에 보여 질 년&월 도서 수 요청 관련 파일 추가 - timeLineReadingListApi.ts
- 타임라인 관련 타입 정의 파일 추가 - timeLine.ts
- 이번 달 독서 리스트 관련 타입 정의 파일 수정 - monthReadingList.ts
<br/>
*
<br/>
*
> 타입 정의 및 header 삭제

- ReadingLogFrontend/src/api/myFavoriteListApi.ts
- ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/types/myFavoriteList.ts
* 
<br/>
*  관심도서 관련 타입정의 파일 추가 - myFavoriteList.ts
* 관심도서 요청 API 코드 파일 추가 - myFavoriteListApi.ts
<br/>
*
<br/>
*
> 관심도서 API 요청 및 타입 파일 추가

- ReadingLogFrontend/src/api/myReadingListApi.ts
- ReadingLogFrontend/src/components/common/BookImgList.tsx
- ReadingLogFrontend/src/components/homeLeft/MyBookList.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_all.json
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_all2.json
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_complete.json
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_complete2.json
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_noRead.json
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_noRead2.json
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_reading.json
- ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_reading2.json
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/types/aladinApi.ts
- ReadingLogFrontend/src/types/monthReadingList.ts
- ReadingLogFrontend/src/types/myFavoriteList.ts
- ReadingLogFrontend/src/types/myReadingList.ts
- ReadingLogFrontend/src/types/readStatus.ts
* #57 
<br/>
* 도서 필터별로 API 요청 구조를 작성하였습니다. 각각 요청에 따른 목데이터 파일을 추가 하였습니다.
* 무한 스크롤 구현
<br/>
*
<br/>
*
> 도서 필터별로 API 요청 구조 작성 및 각 요청 별로 리스트 표시 및 무한스크롤 구현

- ReadingLogBackend/src/main/java/com/example/demo/user/Controller/UserController.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Entity/KakaoProfile.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Entity/KakaoTokenResponse.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Entity/User.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Service/ApiKeyService.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Service/KakaoService.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Service/UserService.java
* #37 
<br/>
* 
<br/>
*
<br/>
*
> 카카오 로그인 구현

- ReadingLogBackend/docker-compose.yml
* - 
<br/>
* 알라딘 키 docker-compose 추가 
<br/>
*
<br/>
*
> 알라딘 API 키 추가 

- ReadingLogBackend/src/main/java/com/example/demo/user/Service/RefreshTokenService.java
* #83 
<br/>
* 
<br/>
*
<br/>
*
> 유저 : 토큰 미일치 시 수정 기능 추가

- ReadingLogFrontend/src/api/myReadingListSearchQueryApi.ts
- ReadingLogFrontend/src/components/common/BookImgList.tsx
- ReadingLogFrontend/src/components/homeLeft/MyBookList.tsx
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/types/myReadingList.ts
- ReadingLogFrontend/tailwind.config.js
* #79 
<br/>
* 내 독서 목록 내부 검색 시 관련된 도서 목록 요청 Api 코드 추가 했습니다.
* 필터링된 도서를 가져오는 부분은 목데이터에 있는 내 독서목록을 가져와 조건물을 통해 필터링 된 도서를 표시하도록 코드를 작성해두었습니다.
* 
*
<br/>
*
> 내 독서 목록 필터 별 검색 독서 리스트 가져오기 (Mock 데이터 사용)

- ReadingLogBackend/src/main/java/com/example/demo/aladinApi/AladinController.java
* #90 
<br/>
* 
<br/>
*
<br/>
*
> Update AladinController.java edit

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/view/social/OAuthCallbackHandler.tsx
* 
<br/>
* 백엔드와 response body 맞춰서 수정
<br/>
*
<br/>
*
> FE) 소셜 로그인 response body 수정

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/api/aladinApi.ts
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
- ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
- ReadingLogFrontend/src/types/timeLine.ts
* 
<br/>
* 요청 중일 때 또 요청이 가지 않도록 코드 추가
const [isFetching, setIsFetching] = useState<boolean>(false);
검색어 입력 후 0.5초 
<br/>
*
<br/>
*
> 알라딘 요청 api 수정

- ReadingLogBackend/src/main/java/com/example/demo/user/Entity/KakaoProfile.java
- ReadingLogBackend/src/main/java/com/example/demo/user/Repository/RefreshTokenRepository.java
> 이서연 : backdev 배포용

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/components/homeTop/Account.tsx
- ReadingLogFrontend/src/mocks/handlers/userHandlers.ts
- ReadingLogFrontend/src/routes/ProtectedRoute.tsx
- ReadingLogFrontend/src/store/userStore.ts
- ReadingLogFrontend/src/view/social/OAuthCallbackHandler.tsx
* #100 
<br/>
* 
<br/>
*
<br/>
*
> 로그인 userState 수정

- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/types/timeLine.ts
* #102 
<br/>
* 
<br/>
*
<br/>
*
> 타임라인 월 표시 및 라인 관련 코드 정리

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/api/ThisMonthReadingListApi.ts
- ReadingLogFrontend/src/api/aladinApi.ts
- ReadingLogFrontend/src/api/allReadingTimeApi.ts
- ReadingLogFrontend/src/api/myFavoriteListApi.ts
- ReadingLogFrontend/src/api/myReadingListApi.ts
- ReadingLogFrontend/src/api/myReadingListSearchQueryApi.ts
- ReadingLogFrontend/src/api/statsMonthApi.ts
- ReadingLogFrontend/src/api/statsYearApi.ts
- ReadingLogFrontend/src/api/timeLineReadingListApi.ts
- ReadingLogFrontend/src/api/todayReadingTimeApi.ts
- ReadingLogFrontend/src/components/common/TodayReadingTime.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
- ReadingLogFrontend/src/mocks/dummyData/statsYearListData/statsYearList.json
- ReadingLogFrontend/src/mocks/handlers/readingRecordHandlers.ts
- ReadingLogFrontend/src/types/statsYear.ts
- ReadingLogFrontend/tailwind.config.js
* #115  
<br/>
* 
<br/>
*
<br/>
*
> 연별 통계 페이지 수정

- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemStopWatch.tsx
- ReadingLogFrontend/src/components/modal/ModalNotice.tsx
- ReadingLogFrontend/src/types/modal.ts
- ReadingLogFrontend/src/utils/createReadingRecord.ts
> 스탑워치 초 단위로 변경 및 중지 시 타이머 정지 기능 추가

- ReadingLogBackend/src/main/java/com/example/demo/aladinApi/AladinController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingList.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListReaponseDto.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListService.java
- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecord.java
- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordService.java
* #90 
* #92 
<br/>
* 도서 리스트 기능 개발  (2개 제외) 
* 독서 기록 응답 값 수정 
* 알라딘API 리턴 시 추가 응답 값 설정 
<br/>
> 알라딘 서버 API, 독서통계, 도서리스트 개발 

- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListService.java
* #129 
<br/>
* 이번달 독서 리스트 api 신규 추가
<br/>
*
<br/>
*
> readinglist 이번 달 독서 리스트

- ReadingLogBackend/src/main/java/com/example/demo/WebConfig.java
- ReadingLogBackend/src/main/java/com/example/demo/aladinApi/AladinController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListRepository.java
> B reading list 관심도서인것만 알라딘 응답값에 포함 시키기

- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListDto.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListService.java
* #130 번
* 
<br/>
* 이번달 -> 월별로 변경 (@inging-bo 요청)
* 반환 값 변경
* interested 도서 제외 
* 
<br/>
*
<br/>
*
> BE readinglist 월별 독서 리스트

- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListService.java
> 이서연 : service 복구

- ReadingLogFrontend/src/api/ThisMonthReadingListApi.ts
- ReadingLogFrontend/src/components/common/CustomScrollbar.tsx
- ReadingLogFrontend/src/components/common/MonthBookImgList.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/types/monthReadingList.ts
- ReadingLogFrontend/src/types/statsYear.ts
> 네이밍 수정 및 css 수정

- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingCountByMonthDto.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingCountStatsResponse.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListController.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListRepository.java
- ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListService.java
* #131 
<br/>
* 년월별 상태별 도서 수 카운트
→ 5 ~ 6 월 독서하는 도서의 경우, 같은 도서에 대해 각 월에 한권씩 추가 
→ 5 ~ 10월 독서 계획있는 읽기 전 도서의 경우에도 각 월에 읽기 전으로 카운트
<br/>
*
<br/>
*
> 타임라인에 보여질 년월별 도서 목록

- ReadingLogBackend/src/main/java/com/example/demo/user/Service/ApiKeyService.java
어노테이션 오류 수정
* 
<br/>
* 
<br/>
*
<br/>
*
> kakao app admin key 어노테이션 수정

- .github/workflows/deploy.yml
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemStopWatch.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemTimer.tsx
- ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
- ReadingLogFrontend/src/mocks/handlers/readingRecordHandlers.ts
* #96 
<br/>
* 
<br/>
*
<br/>
*
> 타이머 독서 시간 기록

- ReadingLogFrontend/src/components/common/BookImgList.tsx
- ReadingLogFrontend/src/components/common/MonthBookImgList.tsx
- ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
- ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
- ReadingLogFrontend/src/components/layout/LeftPage.tsx
- ReadingLogFrontend/tailwind.config.js
> 독서 상태 변경시 리렌더링 및 타임라인 표시 수정

- ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
- ReadingLogFrontend/src/mocks/handlers/userHandlers.ts
> 회원 탈퇴시 모달 오류 수정

- ReadingLogFrontend/src/components/common/BookImgList.tsx
- ReadingLogFrontend/src/components/common/MonthBookImgList.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxStopWatch.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxTimer.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
- ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
- ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
- ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
- ReadingLogFrontend/src/types/monthReadingList.ts
- ReadingLogFrontend/src/types/readingListAdd.ts
- ReadingLogFrontend/tailwind.config.js
*  #165 
* #167 
<br/>
* 
<br/>
*
<br/>
*
> 독서 상태 변경 관련 수정 사항

- ReadingLogFrontend/src/components/common/BookImgList.tsx
- ReadingLogFrontend/src/components/common/WarningScreen.tsx
- ReadingLogFrontend/src/components/common/YearSlideBar.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxStopWatch.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxTimer.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemStopWatch.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemTimer.tsx
- ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
- ReadingLogFrontend/src/components/modal/ModalCalendar.tsx
- ReadingLogFrontend/src/components/modal/ModalNotice.tsx
- ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
- ReadingLogFrontend/src/store/useReadingInfoStore.ts
*  #172 
* #168 
<br/>
* 
<br/>
*
<br/>
*
> 독서 중 일때 제어 관련 수정

- ReadingLogFrontend/src/App.tsx
- ReadingLogFrontend/src/components/common/TooltipInfo.tsx
- ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
- ReadingLogFrontend/src/mocks/dummyData/statsMonthListData/statsMonthList.json
- ReadingLogFrontend/src/mocks/dummyData/statsYearListData/statsYearList.json
- ReadingLogFrontend/src/store/useReadingInfoStore.ts
- ReadingLogFrontend/src/store/useTooltipStore.ts
- ReadingLogFrontend/src/types/statsMonth.ts
- ReadingLogFrontend/tailwind.config.js
* #174 
* #175 
<br/>
* 
<br/>
*
<br/>
*
> 독서 타임 트래킹 중인 도서 이번 달 독서 리스트에 표시 되도록 수정, 월별 통계 그래프에 도서 호버시 책 정보 표시

- ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
- ReadingLogFrontend/src/components/modal/ModalNotice.tsx
> 알림 모달 간격 수정 및 멘트 수정

- ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
- ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
- ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
- ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
- ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
- ReadingLogFrontend/src/main.tsx
- ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
- ReadingLogFrontend/src/mocks/handlers/readingRecordHandlers.ts
- ReadingLogFrontend/src/store/useGlobalChangeStore.ts
* #22 
<br/>
* 
<br/>
*
<br/>
*
> UI 수정 및 api 요청 정리

- ReadingLogFrontend/src/components/common/BookImgList.tsx
- ReadingLogFrontend/src/components/common/TooltipInfo.tsx
- ReadingLogFrontend/src/components/homeTop/Account.tsx
- ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
- ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
- ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
- ReadingLogFrontend/src/mocks/dummyData/statsMonthListData/statsMonthList.json
> 알림 모달에 안들어간 모션효과 추가
